version: '3'

services:
  be_jamugo:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    ports:
      - "3009:3009"
    env_file:
      - .env
    extra_hosts:
      - "host.docker.internal:172.17.0.1"

  mysql:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: "@JamuGo17"
      MYSQL_DATABASE: db_jamugo
      MYSQL_USER: root
      MYSQL_PASSWORD: "@JamuGo17"
    ports:
      - "3307:3306"
    volumes:
      - db_data:/var/lib/mysql
    command: --default-authentication-plugin=mysql_native_password

volumes:
  db_data:
