version: '3'

services:
  be_jamugo:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    ports:
      - "3009:3009"
    env_file:
      - .env
    extra_hosts:
      - "host.docker.internal:172.17.0.1"
